//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivosFijos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int Codigo_Empleado { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Cedula { get; set; }
        public int Codigo_Departamento { get; set; }
        public string Tipo_Persona { get; set; }
        public System.DateTime Fecha_Ingreso { get; set; }
        public string Estado { get; set; }
    
        public virtual Departamento Departamento { get; set; }
    }
}
