//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivosFijos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activos_Fijos_Info
    {
        public int Id { get; set; }
        public int Codigo_Activo { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Serie { get; set; }
        public string Color { get; set; }
        public string Factura { get; set; }
        public string InfoAdicional { get; set; }
    
        public virtual Activos_Fijos Activos_Fijos { get; set; }
    }
}
