//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivosFijos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calculo_Depreciacion
    {
        public int Codigo_Registro { get; set; }
        public int Codigo_Activo_Fijo { get; set; }
        public System.DateTime Fecha_Proceso { get; set; }
        public decimal Monto_Depreciado { get; set; }
        public decimal Depreciacion_Acumulada { get; set; }
    
        public virtual Activos_Fijos Activos_Fijos { get; set; }
    }
}
