//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivosFijos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calculo_Depreciacion
    {
        public int Codigo_Registro { get; set; }
        public int Codigo_Activo_Fijo { get; set; }
        public System.DateTime Fecha_Proceso { get; set; }
        public decimal Monto_Depreciado { get; set; }
        public decimal Depreciacion_Acumulada { get; set; }
    
        public virtual Activos_Fijos Activos_Fijos { get; set; }
    }
}
