//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivosFijos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ActivosEntities : DbContext
    {
        public ActivosEntities()
            : base("name=ActivosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activos_Fijos> Activos_Fijos { get; set; }
        public virtual DbSet<Calculo_Depreciacion> Calculo_Depreciacion { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Parametro> Parametro { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Tipo_Activo> Tipo_Activo { get; set; }
        public virtual DbSet<Tipo_Pago> Tipo_Pago { get; set; }
        public virtual DbSet<Ubicacion> Ubicacion { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<v_Activosfijos> v_Activosfijos { get; set; }
        public virtual DbSet<MovimientosActivos> MovimientosActivos { get; set; }
    
        public virtual int pa_depreciaActivos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_depreciaActivos");
        }
    }
}
