//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivosFijos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientosActivos
    {
        public int Id { get; set; }
        public int Codigo_Activo_Fijo { get; set; }
        public string Tipo_Movimiento { get; set; }
        public System.DateTime Fecha_Movimiento { get; set; }
        public int Codigo_Ubicacion { get; set; }
        public int Codigo_Departamento { get; set; }
        public int Codigo_Proveedor { get; set; }
        public int Codigo_Responsable { get; set; }
        public int Codigo_TipoActivo { get; set; }
        public int Codigo_Usuario { get; set; }
        public string Descripcion { get; set; }
        public string Depreciar { get; set; }
        public string Estado { get; set; }
        public decimal Valor { get; set; }
    
        public virtual Activos_Fijos Activos_Fijos { get; set; }
        public virtual Departamento Departamento { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual Tipo_Activo Tipo_Activo { get; set; }
        public virtual Ubicacion Ubicacion { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
