//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivosFijos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametro
    {
        public int Codigo_Parametro { get; set; }
        public Nullable<System.DateTime> Ano_Mes_Proceso { get; set; }
        public Nullable<bool> Deprec_Calculada { get; set; }
        public string RNC_Empresa { get; set; }
        public string Met_Drepeciacion { get; set; }
    }
}
