//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivosFijos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametro
    {
        public int Codigo_Parametro { get; set; }
        public Nullable<System.DateTime> Ano_Mes_Proceso { get; set; }
        public Nullable<bool> Deprec_Calculada { get; set; }
        public string RNC_Empresa { get; set; }
        public string Met_Drepeciacion { get; set; }
    }
}
