//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivosFijos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        public int Codigo_Proveedor { get; set; }
        public string Nombre { get; set; }
        public string Cedula_RNC { get; set; }
        public string Tipo_Proveedor { get; set; }
        public System.DateTime Fecha_Registro { get; set; }
        public string Estado { get; set; }
    }
}
