//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivosFijos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Activo
    {
        public int Codigo_TipoActivo { get; set; }
        public string Descripcion { get; set; }
        public string Cuenta_ContCompra { get; set; }
        public string Cuenta_ContDeprec { get; set; }
        public string Estado { get; set; }
    }
}
