//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivosFijos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Activo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tipo_Activo()
        {
            this.Activos_Fijos = new HashSet<Activos_Fijos>();
        }
    
        public int Codigo_TipoActivo { get; set; }
        public string Descripcion { get; set; }
        public string Estado { get; set; }
        public Nullable<int> VidaUtil { get; set; }
        public Nullable<decimal> Porcentaje { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activos_Fijos> Activos_Fijos { get; set; }
    }
}
