//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivosFijos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Activosfijos
    {
        public string CodigoBR { get; set; }
        public int Codigo { get; set; }
        public string Descripcion { get; set; }
        public string Proveedor { get; set; }
        public string Departamento { get; set; }
        public string Ubicacion { get; set; }
        public string TipoActivo { get; set; }
        public string Depreciar { get; set; }
        public string Responsable { get; set; }
        public System.DateTime FechaCompra { get; set; }
        public decimal ValorCompra { get; set; }
        public Nullable<decimal> PorDepAnual { get; set; }
        public Nullable<decimal> PorDepMensual { get; set; }
        public Nullable<decimal> PorDepDiaria { get; set; }
        public Nullable<System.DateTime> FechaUltDepreciacion { get; set; }
        public Nullable<decimal> Depreciado { get; set; }
        public Nullable<decimal> Acumulado { get; set; }
        public Nullable<decimal> PorDepreciar { get; set; }
    }
}
