//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivosFijos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        public int Codigo_Proveedor { get; set; }
        public string Nombre { get; set; }
        public string Cedula_RNC { get; set; }
        public string Tipo_Proveedor { get; set; }
        public System.DateTime Fecha_Registro { get; set; }
        public string Estado { get; set; }
    }
}
